// <auto-generated />
using System;
using Mehrak.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mehrak.Infrastructure.Migrations.ReleaseNoteDb
{
    [DbContext(typeof(ReleaseNoteDbContext))]
    [Migration("20260524082617_OptionalDate")]
    partial class OptionalDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mehrak.Infrastructure.Models.ReleaseVersionModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Date")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Version")
                        .IsUnique();

                    b.ToTable("ReleaseVersions");
                });

            modelBuilder.Entity("Mehrak.Infrastructure.Models.ReleaseVersionModel", b =>
                {
                    b.OwnsMany("Mehrak.Infrastructure.Models.ReleaseNoteSection", "Sections", b1 =>
                        {
                            b1.Property<Guid>("ReleaseVersionModelId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200);

                            b1.HasKey("ReleaseVersionModelId", "__synthesizedOrdinal");

                            b1.ToTable("ReleaseVersions");

                            b1
                                .ToJson("Sections")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ReleaseVersionModelId");

                            b1.OwnsMany("Mehrak.Infrastructure.Models.ReleaseNoteEntry", "Notes", b2 =>
                                {
                                    b2.Property<Guid>("ReleaseNoteSectionReleaseVersionModelId");

                                    b2.Property<int>("ReleaseNoteSection__synthesizedOrdinal");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("Text")
                                        .IsRequired()
                                        .HasMaxLength(2000);

                                    b2.Property<string>("Type")
                                        .IsRequired()
                                        .HasMaxLength(50);

                                    b2.HasKey("ReleaseNoteSectionReleaseVersionModelId", "ReleaseNoteSection__synthesizedOrdinal", "__synthesizedOrdinal");

                                    b2.ToTable("ReleaseVersions");

                                    b2.WithOwner()
                                        .HasForeignKey("ReleaseNoteSectionReleaseVersionModelId", "ReleaseNoteSection__synthesizedOrdinal");
                                });

                            b1.Navigation("Notes");
                        });

                    b.Navigation("Sections");
                });
#pragma warning restore 612, 618
        }
    }
}
