// <auto-generated />
using System;
using Mehrak.Infrastructure.User;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mehrak.Infrastructure.Migrations
{
    [DbContext(typeof(UserDbContext))]
    partial class UserDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mehrak.Infrastructure.Models.ProfileGameUid", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Game")
                        .HasColumnType("integer");

                    b.Property<string>("GameUid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("GameUids", (string)null);
                });

            modelBuilder.Entity("Mehrak.Infrastructure.Models.ProfileRegion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Game")
                        .HasColumnType("integer");

                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("Regions", (string)null);
                });

            modelBuilder.Entity("Mehrak.Infrastructure.Models.UserModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Mehrak.Infrastructure.Models.UserProfileModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("LToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastCheckIn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LtUid")
                        .HasColumnType("bigint");

                    b.Property<int>("ProfileId")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("LtUid");

                    b.HasIndex("UserId", "ProfileId")
                        .IsUnique();

                    b.ToTable("UserProfiles", (string)null);
                });

            modelBuilder.Entity("Mehrak.Infrastructure.Models.ProfileGameUid", b =>
                {
                    b.HasOne("Mehrak.Infrastructure.Models.UserProfileModel", "UserProfile")
                        .WithMany("GameUids")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Mehrak.Infrastructure.Models.ProfileRegion", b =>
                {
                    b.HasOne("Mehrak.Infrastructure.Models.UserProfileModel", "UserProfile")
                        .WithMany("LastUsedRegions")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Mehrak.Infrastructure.Models.UserProfileModel", b =>
                {
                    b.HasOne("Mehrak.Infrastructure.Models.UserModel", "User")
                        .WithMany("Profiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mehrak.Infrastructure.Models.UserModel", b =>
                {
                    b.Navigation("Profiles");
                });

            modelBuilder.Entity("Mehrak.Infrastructure.Models.UserProfileModel", b =>
                {
                    b.Navigation("GameUids");

                    b.Navigation("LastUsedRegions");
                });
#pragma warning restore 612, 618
        }
    }
}
