// <auto-generated />
using System;
using System.Collections.Generic;
using Mehrak.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mehrak.Infrastructure.Migrations.DocumentationDb
{
    [DbContext(typeof(DocumentationDbContext))]
    partial class DocumentationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mehrak.Infrastructure.Models.DocumentationModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.PrimitiveCollection<List<string>>("Examples")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("Game")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Game");

                    b.HasIndex("Name");

                    b.ToTable("Documentations");
                });

            modelBuilder.Entity("Mehrak.Infrastructure.Models.DocumentationModel", b =>
                {
                    b.OwnsMany("Mehrak.Infrastructure.Models.DocumentationParameter", "Parameters", b1 =>
                        {
                            b1.Property<Guid>("DocumentationModelId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(200);

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(50);

                            b1.Property<bool>("Required");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(50);

                            b1.HasKey("DocumentationModelId", "__synthesizedOrdinal");

                            b1.ToTable("Documentations");

                            b1
                                .ToJson("Parameters")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("DocumentationModelId");
                        });

                    b.Navigation("Parameters");
                });
#pragma warning restore 612, 618
        }
    }
}
