{
 "title": "Mehrak Dashboard",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "log_level", "label": "Log Level", "query": "Information, Warning, Error" }
  ]
 },
 "panels": [
  { "title": "System Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System CPU Usage",
   "type": "timeseries",
   "description": "CPU usage percentage of the VPS",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "CPU Usage %",
     "rawSql": "SELECT\r\n  TimeUnix as time,\r\n  Attributes['cpu'] AS cpu_core,\r\n  100 * (1 - avg(Value)) AS cpu_utilization\r\nFROM otel_metrics_gauge\r\nWHERE\r\n  $__timeFilter(TimeUnix)\r\n  AND MetricName = 'system.cpu.utilization'\r\n  AND Attributes['state'] = 'idle'\r\nGROUP BY \r\n  time,\r\n  cpu_core\r\nORDER BY \r\n  TimeUnix,\r\n  cpu_core ASC"
    }
   ]
  },
  {
   "title": "System Memory Usage",
   "type": "timeseries",
   "description": "Memory usage of the VPS",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes",
     "legendFormat": "Used Memory",
     "rawSql": "SELECT\r\n    TimeUnix,\r\n    Value\r\nFROM \r\n    otel_metrics_sum\r\nWHERE\r\n    $__timeFilter(TimeUnix)\r\n    AND MetricName = 'system.memory.usage'\r\n    AND Attributes['state'] = 'used'"
    },
    {
     "rawSql": "SELECT\r\n    TimeUnix,\r\n    avg(Value) AS value\r\nFROM \r\n    otel_metrics_sum\r\nWHERE\r\n    $__timeFilter(TimeUnix)\r\n    AND MetricName = 'system.memory.limit'\r\nGROUP BY \r\n    TimeUnix\r\nORDER BY \r\n    TimeUnix"
    }
   ]
  },
  { "title": "Mehrak Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Discord Latency (ms)",
   "type": "timeseries",
   "description": "Discord Gateway client latency (ms)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "discord_bot_latency_ms",
     "legendFormat": "__auto",
     "rawSql": "SELECT \r\n    TimeUnix,\r\n    Value\r\nFROM otel_metrics_gauge\r\nWHERE\r\n    $__timeFilter(TimeUnix)\r\n    AND MetricName = 'bot_latency_ms'"
    }
   ]
  },
  {
   "title": "Command Success Rate",
   "type": "timeseries",
   "description": "Success rate of command execution",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\r\n  sum(rate(discord_command_results{result=\"success\"}[5m])) \r\n  / \r\n  (sum(rate(discord_command_results[5m])) > 0) * 100\r\n) OR on() vector(100)",
     "legendFormat": "Success",
     "rawSql": "SELECT\r\n    time,\r\n    if(total_commands > 0, (success_commands / total_commands) * 100, 100) AS success_rate\r\nFROM\r\n(\r\n    SELECT\r\n        toStartOfInterval(TimeUnix, INTERVAL $__interval_s second) AS time,\r\n        sumIf(Value, Attributes['result'] = 'success') AS success_commands,\r\n        sum(Value) AS total_commands\r\n    FROM otel_metrics_sum\r\n    WHERE MetricName = 'bot_command_results'\r\n      AND $__timeFilter(TimeUnix)\r\n    GROUP BY time\r\n    ORDER BY time ASC WITH FILL STEP $__interval_s\r\n)"
    }
   ]
  },
  {
   "title": "Command Rate",
   "type": "timeseries",
   "description": "Total commands executed over time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(discord_commands_total[5m])",
     "legendFormat": "Commands per second",
     "rawSql": "SELECT\r\n    toStartOfInterval(TimeUnix, INTERVAL $__interval_s second) AS time,\r\n    sum(Value) / ($__interval_s / 60) AS commands_per_min\r\nFROM otel_metrics_sum\r\nWHERE MetricName = 'bot_command_by_user'\r\n  AND $__timeFilter(TimeUnix)\r\nGROUP BY time\r\nORDER BY time ASC WITH FILL STEP $__interval_s"
    }
   ]
  },
  {
   "title": "Top Commands",
   "type": "barchart",
   "description": "Top commands used",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (command_name) (floor(increase(discord_commands_by_name[$__range])))",
     "legendFormat": "{{command_name}}",
     "rawSql": "SELECT\r\n    Attributes['command_name'] AS command_name,\r\n    sum(Value) AS total_executions\r\nFROM otel_metrics_sum\r\nWHERE MetricName = 'bot_command_results'\r\n  AND $__timeFilter(TimeUnix)\r\nGROUP BY command_name\r\nORDER BY total_executions DESC\r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Command Execution Time",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \r\n  sum by (command_name, le) (\r\n    rate(discord_command_exec_time_bucket[5m])\r\n  )\r\n)",
     "legendFormat": "{{command_name}}",
     "rawSql": "SELECT\r\n  quantile(0.95)(Min) as average,\r\n  Attributes['command_name'] as command\r\nFROM otel_metrics_histogram\r\nWHERE\r\n  MetricName = 'bot_command_exec_time'\r\n  AND $__timeFilter(TimeUnix)\r\nGROUP BY command\r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Top Users",
   "type": "barchart",
   "description": "Top users by command usage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(10, sum by (user_id) (floor(increase(discord_commands_by_user[$__range]))))",
     "legendFormat": "{{user_id}}",
     "rawSql": "SELECT\r\n    Attributes['user_id'] AS user_id,\r\n    sum(Value) AS total_invocations\r\nFROM otel_metrics_sum\r\nWHERE MetricName = 'bot_command_by_user'\r\n  AND $__timeFilter(TimeUnix)\r\nGROUP BY user_id\r\nORDER BY total_invocations DESC\r\nLIMIT 10"
    }
   ]
  },
  { "title": "Game Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Popular Characters (Genshin)",
   "type": "barchart",
   "description": "Most popular character in Genshin among users",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "topk(10, sum by (character) (increase(discord_character_selections_total{game=\"Genshin\"}[$__range])))",
     "legendFormat": "{{character}}",
     "rawSql": "SELECT\r\n    Attributes['character'] AS character,\r\n    sum(Value) AS total_count\r\nFROM otel_metrics_sum\r\nWHERE MetricName = 'application_character_selections_total'\r\n  AND $__timeFilter(TimeUnix)\r\n  AND Attributes['game'] = 'Genshin'\r\nGROUP BY character\r\nORDER BY total_count DESC\r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Most popular character (HSR)",
   "type": "barchart",
   "description": "Most popular character in HSR among users",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "topk(10, sum by (character) (increase(discord_character_selections_total{game=\"HonkaiStarRail\"}[$__range])))",
     "legendFormat": "{{character}}",
     "rawSql": "SELECT\r\n    Attributes['character'] AS character,\r\n    sum(Value) AS total_count\r\nFROM otel_metrics_sum\r\nWHERE MetricName = 'application_character_selections_total'\r\n  AND $__timeFilter(TimeUnix)\r\n  AND Attributes['game'] = 'HonkaiStarRail'\r\nGROUP BY character\r\nORDER BY total_count DESC\r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Popular Characters (Zenless Zone Zero)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "topk(10, sum by (character) (increase(discord_character_selections_total{game=\"ZenlessZoneZero\"}[$__range])))",
     "legendFormat": "{{character}}",
     "rawSql": "SELECT\r\n    Attributes['character'] AS character,\r\n    sum(Value) AS total_count\r\nFROM otel_metrics_sum\r\nWHERE MetricName = 'application_character_selections_total'\r\n  AND $__timeFilter(TimeUnix)\r\n  AND Attributes['game'] = 'ZenlessZoneZero'\r\nGROUP BY character\r\nORDER BY total_count DESC\r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Popular Characters (Honkai Impact 3rd)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "topk(10, sum by (character) (increase(discord_character_selections_total{game=\"HonkaiImpact3\"}[$__range])))",
     "legendFormat": "{{character}}",
     "rawSql": "SELECT\r\n    Attributes['character'] AS character,\r\n    sum(Value) AS total_count\r\nFROM otel_metrics_sum\r\nWHERE MetricName = 'application_character_selections_total'\r\n  AND $__timeFilter(TimeUnix)\r\n  AND Attributes['game'] = 'HonkaiImpact3'\r\nGROUP BY character\r\nORDER BY total_count DESC\r\nLIMIT 10"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"MehrakBot\"} | json | level=~\"${log_level:regex}\" | line_format \"[{{.SourceContext}}]: {{.Message}}\"",
     "rawSql": "SELECT\r\n    Timestamp AS time,\r\n    Body AS message,\r\n    SeverityText AS level,\r\n    ServiceName,\r\n    TraceId AS traceID,\r\n    toJSONString(LogAttributes) as attributes\r\nFROM \r\n    otel_logs\r\nWHERE \r\n    $__timeFilter(Timestamp)\r\n    AND SeverityText IN (${log_level:singlequote})\r\nORDER BY \r\n    Timestamp DESC\r\nLIMIT 1000"
    }
   ]
  }
 ]
}