//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MehrakCore.Resources.Modules {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommandStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommandStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MehrakCore.Resources.Modules.CommandStrings", typeof(CommandStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid UID!.
        /// </summary>
        internal static string AddAuthModalInvalidUIDMessage {
            get {
                return ResourceManager.GetString("AddAuthModalInvalidUIDMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticated successfully..
        /// </summary>
        internal static string AddAuthModalSuccessfulMessage {
            get {
                return ResourceManager.GetString("AddAuthModalSuccessfulMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not use the same password as your Discord or HoYoLAB account!.
        /// </summary>
        internal static string AddAuthPassphrasePlaceholder {
            get {
                return ResourceManager.GetString("AddAuthPassphrasePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passphrase.
        /// </summary>
        internal static string AuthModalPassphraseLabel {
            get {
                return ResourceManager.GetString("AuthModalPassphraseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticate.
        /// </summary>
        internal static string AuthModalTitle {
            get {
                return ResourceManager.GetString("AuthModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication timed out, please try again..
        /// </summary>
        internal static string AuthTimeoutErrorMessage {
            get {
                return ResourceManager.GetString("AuthTimeoutErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid passphrase!.
        /// </summary>
        internal static string AuthUserInvalidPassphraseMessage {
            get {
                return ResourceManager.GetString("AuthUserInvalidPassphraseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No profile found! Please add a profile first..
        /// </summary>
        internal static string AuthUserNoProfileMessage {
            get {
                return ResourceManager.GetString("AuthUserNoProfileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character not found. Please try again..
        /// </summary>
        internal static string CharacterNotFoundErrorMessage {
            get {
                return ResourceManager.GetString("CharacterNotFoundErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve character data. Please try again..
        /// </summary>
        internal static string CharacterRetrieveUnsuccessfulMessage {
            get {
                return ResourceManager.GetString("CharacterRetrieveUnsuccessfulMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command execution completed..
        /// </summary>
        internal static string CommandExecutionCompletedMessage {
            get {
                return ResourceManager.GetString("CommandExecutionCompletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string Commands_character_Description {
            get {
                return ResourceManager.GetString("Commands_character_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string Commands_character_Name {
            get {
                return ResourceManager.GetString("Commands_character_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string Commands_character_Parameter_character_Description {
            get {
                return ResourceManager.GetString("Commands_character_Parameter_character_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string Commands_character_Parameter_character_Name {
            get {
                return ResourceManager.GetString("Commands_character_Parameter_character_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string Commands_character_Parameter_server_Description {
            get {
                return ResourceManager.GetString("Commands_character_Parameter_server_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string Commands_character_Parameter_server_Name {
            get {
                return ResourceManager.GetString("Commands_character_Parameter_server_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used command too frequent! Please try again later..
        /// </summary>
        internal static string RateLimitErrorMessage {
            get {
                return ResourceManager.GetString("RateLimitErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No game information found. Please select the correct region..
        /// </summary>
        internal static string ServerNoGameInformationErrorMessage {
            get {
                return ResourceManager.GetString("ServerNoGameInformationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request. Please try again later..
        /// </summary>
        internal static string UnknownErrorMessage {
            get {
                return ResourceManager.GetString("UnknownErrorMessage", resourceCulture);
            }
        }
    }
}
