global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'mehrakcore-bot'
    static_configs:
      - targets: [ 'mehrakcore-bot-1:9090' ]  # Using Docker service name
