services:
  bot:
    image: mehrak:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - ./Assets:/assets
      - ./mongodb-entrypoint.sh:/mongodb-entrypoint.sh
    environment:
      - MONGO_INITDB_DATABASE=MehrakBot
    entrypoint: [ "/mongodb-entrypoint.sh" ]
    command: [ ]

volumes:
  mongo_data:
