// <auto-generated />
using System;
using Mehrak.Infrastructure.Character;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mehrak.Infrastructure.Migrations.CharacterDb
{
    [DbContext(typeof(CharacterDbContext))]
    [Migration("20260613065435_UserPortraitActive")]
    partial class UserPortraitActive
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mehrak.Infrastructure.Character.Models.AliasModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Game")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Game", "Alias")
                        .IsUnique();

                    b.ToTable("Aliases");
                });

            modelBuilder.Entity("Mehrak.Infrastructure.Character.Models.CharacterModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float?>("BaseVal")
                        .HasColumnType("real");

                    b.Property<int>("Game")
                        .HasColumnType("integer");

                    b.Property<float?>("MaxAscVal")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Game", "Name")
                        .IsUnique();

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Mehrak.Infrastructure.Character.Models.CharacterPortraitConfigModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("EnableGradientFade")
                        .HasColumnType("boolean");

                    b.Property<int>("Game")
                        .HasColumnType("integer");

                    b.Property<float?>("GradientFadeStart")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("OffsetX")
                        .HasColumnType("integer");

                    b.Property<int?>("OffsetY")
                        .HasColumnType("integer");

                    b.Property<int>("ServerId")
                        .HasColumnType("integer");

                    b.Property<float?>("TargetScale")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("Game", "ServerId")
                        .IsUnique();

                    b.ToTable("CharacterPortraitConfigs");
                });

            modelBuilder.Entity("Mehrak.Infrastructure.Character.Models.CharacterServerIdModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.Property<int>("ServerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId", "ServerId")
                        .IsUnique();

                    b.ToTable("CharacterServerIds");
                });

            modelBuilder.Entity("Mehrak.Infrastructure.Character.Models.UserPortraitConfigModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool?>("EnableGradientFade")
                        .HasColumnType("boolean");

                    b.Property<float?>("GradientFadeStart")
                        .HasColumnType("real");

                    b.Property<int?>("OffsetX")
                        .HasColumnType("integer");

                    b.Property<int?>("OffsetY")
                        .HasColumnType("integer");

                    b.Property<float?>("TargetScale")
                        .HasColumnType("real");

                    b.Property<Guid>("UserPortraitUploadId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserPortraitUploadId")
                        .IsUnique();

                    b.ToTable("UserPortraitConfigs");
                });

            modelBuilder.Entity("Mehrak.Infrastructure.Character.Models.UserPortraitUpload", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DiscordUserId")
                        .HasColumnType("bigint");

                    b.Property<int>("Game")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("S3Key")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("SHA256Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DiscordUserId", "Game", "CharacterName");

                    b.HasIndex("DiscordUserId", "Game", "CharacterName", "IsActive");

                    b.HasIndex("DiscordUserId", "Game", "CharacterName", "SHA256Hash")
                        .IsUnique();

                    b.ToTable("UserPortraitUploads");
                });

            modelBuilder.Entity("Mehrak.Infrastructure.Character.Models.CharacterServerIdModel", b =>
                {
                    b.HasOne("Mehrak.Infrastructure.Character.Models.CharacterModel", "Character")
                        .WithMany("ServerIds")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Mehrak.Infrastructure.Character.Models.UserPortraitConfigModel", b =>
                {
                    b.HasOne("Mehrak.Infrastructure.Character.Models.UserPortraitUpload", "Upload")
                        .WithOne("Config")
                        .HasForeignKey("Mehrak.Infrastructure.Character.Models.UserPortraitConfigModel", "UserPortraitUploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Upload");
                });

            modelBuilder.Entity("Mehrak.Infrastructure.Character.Models.CharacterModel", b =>
                {
                    b.Navigation("ServerIds");
                });

            modelBuilder.Entity("Mehrak.Infrastructure.Character.Models.UserPortraitUpload", b =>
                {
                    b.Navigation("Config")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
