name: Cleanup Old Releases
permissions:
  contents: write
on:
  release:
    types: [published]
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-24.04
    steps:
      - name: Delete old releases (keep 5 minor versions)
        uses: Nats-ji/delete-old-releases@v1.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          keep-count: 5
          keep-old-minor-releases: true
          remove-tags: true
